config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :posts do
  resources :comments
end
 root 'posts#index'

 get '/about' , to: "pages#about"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post<ActiveRecord::Base
	has_many :comments
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence:true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))
		redirect_to post_path(@post)
    end
	
private 
def comment_params 
	params.require(:comment).permit(:name,:body)
end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about 

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user! , except: [:index, :show]

	def index
		@post = Post.all.order('created_at DESC')

	end
	def new 
		@post = Post.new

	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] ="Article has been saved"
			redirect_to @post
	    else
	    	render 'new'
	    end
	end

	def show
		@post = Post.find(params[:id])
	end

	# edit and upate
	def edit
		@post = Post.find(params[:id])
	end


	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			flash[:notice] ="Article has been saved"
			redirect_to @post
	    else
	    	render 'edit'

	    end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end


private 
    def post_params
    	params.require(:post).permit(:title,:body)


    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><%= content.name %></p>
		<p class="comment_body"><%= comment.body%></p>
		<p class="comment_title"><%= time_in_words_ago(comment.created_at)%>Ago</p>
	</div>

</div>

app/views/comments/_form.html.erb
<%= form_for ([@post,@post.comments.build]) do |t| %>
<p>
	<%= t.label :name%>
	<%= t.text_field :name%>
</p>

<p>
	<%= t.label :body%>
	<%= t.text_area :body%>
</p>
<p>
	<%= t.submit %>
</p>
<% end %>

app/views/layouts/_message.html.erb
<% flash.each do |name,msg| %>
<ul>
	<li><%= msg %></li>
</ul>
 <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TumblerClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', "//fonts.googleapis.com/css?family=Raleway:400,700" %>
  <%= favicon_link_tag 'favicon.ico' %>

  <%= csrf_meta_tags %>
</head>
<body>
	<!-- sideBar -->
	<div id="sidebar">
		<ul>
			<li class"category"><%=link_to "Tumblr",root_path%></li>
			<li><%=link_to "Posts",root_path%></li>
			<li><%=link_to "About",about_path%></li>
		</ul>
		<!-- if user is not signed in -->
		<% if !user_signed_in? %>
		<p class="sign_in"><%=link_to "User Login",new_user_session_path%></p>
		<% end %>
	</div>

	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path)%>
			<p>Post Feeds</p>
			<% elsif current_page?(about_path)%>
			<p>My Site</p>
			<%else %>
			<%= link_to "Back to Post Feed" ,root_path %>
			 <% end %>


	<% if user_signed_in? %>	
			<div class="buttons">
		<button class="button"><%=link_to "New Post",new_post_path%></button>
		<button class="button"><%=link_to "Sign Out", destroy_user_session_path, method: :delete%></button>
	
			</div>
		<% end %>
		</div>

        
      <%= yield %>
      <% render 'layouts/message' %>

	</div>



</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag 'profile.jpg' %>
	</div>

</div>

<div id="content">
	<h1>Hi, I am Ashish</h1>
	<p>Simply put, it’s a take on the lorem ipsum filler text used when doing design mockups.  I was mocking up a web design one day and needed a few words to fill out a link.  “Lorem ipsum bacon” popped into my head, so I plugged that into my HTML.  Later that day, it hit me.  Make a lorem ipsum generator but use types and cuts of meat.
    </p>

</div>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	
	<%=form_for @post do |t| %>
	<!-- errors -->
	<% if @post.errors.any? %>
	<div id="errors">
			<% @post.errors.full_messages.each do |t|%>
	<ul>
		<li>
			<%= t %>
		</li>
	</ul>
    <% end %>

	</div>
	<% end %>

	<p><%= t.label :title %>
	<%= t.text_field :title %></p>
	<p><%= t.label :body %>
	 <%= t.text_area :body %></p>
	<p><%= t.submit%></p>
<% end %>
</div>

app/views/posts/index.html.erb
<% @post.each do |post| %>
<div class="post_wrapper">
	<h2 class="title"><%=link_to post.title, post_path(post)%></h2>
	<p class="body"><%= truncate(post.body ,length:100)%></p>
	<p class="date"><%= time_ago_in_words(post.created_at)%></p> 
</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<%=form_for @post do |t| %>
	<p><%= t.label :title %>
	<%= t.text_field :title %></p>
	<p><%= t.label :body %>
	 <%= t.text_area :body %></p>
	<p><%= t.submit%></p>
<% end %>
</div>

app/views/posts/show.html.erb
<div id ="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>
	<p class ="date">
		<% if user_signed_in? %>
		<%= time_ago_in_words(@post.created_at)%> ago|<%=link_to 'Edit',edit_post_path(@post)%>|
		<%=link_to 'Delete',post_path(@post), method: :delete , confirm: {data: "Are you sure you want to delete?"} %>
		<% end %>
    </p>
    <p class="body">
    	<%= @post.body %>
    </p>

    <div class="comment">
    	<p><%= @post.comments.count%> </p>
    	
    	<h3>Join Discussion:</h3>
    	<%= render "comments/form" %>

    </div>

</div>
	